version: '3.8'

services:
 checkout:
  build:
   context: .
  ports:
   - 8080:3010
  environment:
   - CONNECTIONSTRING=mongodb://mongo:27017/checkout
  volumes:
   - ./:/code

mongo:
  image: mongo:4.4.3
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: