version: '3'
services:
 localreview:
  build: 
   context: .
  ports:
   - 3004:3004
  environment:
   - CONNECTIONSTRING=mongodb://mongo:27017/review
  volumes:
   - ./:/code
 mongo:
  image: mongo:4.4.3
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
